import type { Product, Sector, GalleryItem, ProcessStep, FeaturePillar } from '../types';

export const siteConfig = {
  brand: {
    name: 'Table Linens',
    tagline: 'Handcrafted with Care',
    headline: 'Handcrafted with Care. Made for Exceptional Tables.',
    supportingLine: 'Premium handcrafted table linens and hospitality textiles, created with care for hotels, restaurants, resorts and special occasions.',
    description: 'Table Linens creates handcrafted table and hospitality textiles with attention to quality, detail, and presentation.',
    year: '2026',
    domain: 'www.tablelinens.com',
    websiteUrl: 'https://www.tablelinens.com',
  },
  contact: {
    office: '548',
    locality: 'Hokandara',
    country: 'Sri Lanka',
    fullAddress: '548, Hokandara, Sri Lanka',
    phoneDisplay: '072 378 5565',
    phoneRaw: '0723785565',
    phoneTel: 'tel:+94723785565',
    whatsappNumber: '+94723785565',
    whatsappRaw: '94723785565',
    email: 'tablelinen.sl@gmail.com',
    facebookUrl: 'https://web.facebook.com/profile.php?id=100009176816581',
  },
  navLinks: [
    { label: 'About', href: '#about' },
    { label: 'Collection', href: '#collection' },
    { label: 'Embroidery', href: '#embroidery' },
    { label: 'Contact', href: '#contact' },
  ],
  story: {
    eyebrow: 'THE TABLE LINENS STORY',
    headline: 'Thoughtfully Crafted for Beautiful Spaces',
    paragraph1: 'At Table Linens, we believe the smallest details can transform a dining experience. Our handcrafted table linens are created with care, attention to detail and a deep appreciation for quality.',
    paragraph2: 'From elegant table napkins and runners to practical hospitality aprons and customized embroidered pieces, we create textiles designed to complement the character of every space.',
    features: [
      'Bespoke sizing and tailored hems for dining establishments',
      'Option for custom embroidered business & hotel crests',
      'Designed for durability in high-turnover hospitality settings',
      'Natural textured linen, cotton blends & easy-care fabrics',
    ],
  },
  products: [
    {
      id: 'table-napkins',
      number: '01',
      name: 'Table Napkins / Serviettes',
      subtitle: 'Refined Tabletop Essential',
      category: 'Dining Linens',
      description: 'Elegant handcrafted napkins designed to complement refined table settings.',
      image: '/images/table-napkins.jpg',
      altText: 'Handcrafted linen table napkin folded neatly on a dining plate',
      features: ['Hand-folded mitred corner detailing', 'Available in pure linen & rich blends', 'Soft pre-washed hand feel'],
      customization: 'Available With or Without Embroidered Logo',
    },
    {
      id: 'table-runners',
      number: '02',
      name: 'Table Runners',
      subtitle: 'Artisanal Centerpiece Textiles',
      category: 'Dining Linens',
      description: 'Simple, sophisticated runners that add texture and character to every table.',
      image: '/images/table-runners.jpg',
      altText: 'Textured natural linen table runner laid across an artisanal wood dining table',
      features: ['Custom lengths for banquet tables', 'Subtle border stitching', 'Textured weave finishes'],
      customization: 'Available With or Without Embroidered Logo',
    },
    {
      id: 'table-cloths',
      number: '03',
      name: 'Table Cloths',
      subtitle: 'Seamless Hospitality Coverings',
      category: 'Dining Linens',
      description: 'Premium table coverings designed for restaurants, hotels, events and hospitality spaces.',
      image: '/images/table-cloths.jpg',
      altText: 'Elegantly draped tablecloth on luxury restaurant dining tables',
      features: ['Round, rectangular & square tailoring', 'High drape and crease resistance', 'Custom hospitality dimensions'],
      customization: 'Available With or Without Embroidered Logo',
    },
    {
      id: 'cutlery-serviettes',
      number: '04',
      name: 'Cutlery Serviettes',
      subtitle: 'Functional Table Precision',
      category: 'Table Presentation',
      description: 'Practical and elegant solutions for beautifully presented cutlery.',
      image: '/images/cutlery-serviettes.jpg',
      altText: 'Cutlery neatly presented inside a folded linen serviette with fork and knife',
      features: ['Streamlined table setup', 'Prevents cutlery scratch marks', 'Refined folded structure'],
      customization: 'Available With or Without Embroidered Logo',
    },
    {
      id: 'aprons',
      number: '05',
      name: 'Aprons',
      subtitle: 'Front & Back of House Uniforms',
      category: 'Service & Hospitality',
      description: 'Functional handcrafted aprons for hospitality teams.',
      image: '/images/aprons.jpg',
      altText: 'Handcrafted linen chef and server apron with reinforced stitching and utility pockets',
      features: ['Reinforced bar-tacking on stress points', 'Adjustable neck and waist ties', 'Utility service pockets'],
      customization: 'Available With or Without Embroidered Logo',
    },
  ] as Product[],
  embroidery: {
    eyebrow: 'MAKE IT YOURS',
    headline: 'Your Table. Your Identity.',
    body: 'Give your table linens a distinctive identity with custom embroidery. We can create selected products with your hotel, restaurant, resort or business logo — or keep them beautifully simple without embroidery.',
    options: [
      {
        title: 'With Embroidered Logo',
        badge: 'Signature Hospitality Look',
        description: 'Precision thread embroidery representing your crest, monogram, or restaurant logo for an elevated bespoke dining impression.',
        highlights: ['High-density colorfast embroidery threads', 'Positioned according to your exact table folding style', 'Ideal for boutique hotels, fine dining & luxury resorts'],
        image: '/images/embroidery-with-logo.jpg',
        alt: 'Close-up of precise logo embroidery stitched onto linen textile',
      },
      {
        title: 'Without Logo',
        badge: 'Clean & Timeless Minimalism',
        description: 'Pristine, understated textiles showcasing the raw beauty of fine natural weave, tailored hemming, and neutral tones.',
        highlights: ['Pure natural fabric texture and drape', 'Versatile across varying seasonal table themes', 'Minimalist elegance for modern cafés & catering'],
        image: '/images/embroidery-without-logo.jpg',
        alt: 'Clean minimalist unbranded linen napkin in neutral tone',
      },
    ],
  },
  hospitalitySectors: [
    {
      id: 'hotels-resorts',
      title: 'Hotels & Resorts',
      badge: 'Luxury Stays',
      description: 'Linens tailored for breakfast buffets, fine dining restaurants, banquet halls, private villas, and suite dining.',
      image: '/images/hero-bg.jpg',
    },
    {
      id: 'restaurants-cafes',
      title: 'Restaurants & Cafés',
      badge: 'Bistros & Fine Dining',
      description: 'Table accessories designed to elevate table turnover presentation, from modern urban cafés to waterfront dining rooms.',
      image: '/images/gallery-5.jpg',
    },
    {
      id: 'catering-events',
      title: 'Catering & Events',
      badge: 'Banquets & Celebrations',
      description: 'Reliable table coverings and serviette collections prepared for grand weddings, private corporate banquets, and event planners.',
      image: '/images/table-cloths.jpg',
    },
    {
      id: 'guest-experiences',
      title: 'Guest Experiences',
      badge: 'Specialty Dining',
      description: 'Distinctive textiles including cutlery serviettes, custom aprons, and tailored table linens designed for guest interaction.',
      image: '/images/story-craft.jpg',
    },
  ] as Sector[],
  maldivesFeature: {
    eyebrow: 'REGIONAL HOSPITALITY REACH',
    headline: 'Hospitality Beyond Borders',
    body: 'Our handcrafted hospitality textiles are also suited to resort and hotel environments where presentation and attention to detail matter.',
    highlightTitle: 'Serviettes & Table Linens for Maldives Hospitality',
    highlightDescription: 'Engineered to withstand coastal ocean climates while preserving an unmistakable tactile luxury. We supply bespoke table serviettes and linens to island resorts prioritizing distinct guest presentation.',
    image: '/images/gallery-8.jpg',
    bulletPoints: [
      'Moisture-friendly, breathable natural blends',
      'Cutlery serviettes designed for outdoor beachfront and overwater dining',
      'Custom monogramming for island villas and private dining',
      'Reliable regional delivery coordination',
    ],
  },
  whyChooseUs: [
    {
      id: 'handcrafted',
      title: 'Handcrafted with Care',
      description: 'Every piece is created with attention to detail and presentation.',
      iconName: 'Sparkles',
    },
    {
      id: 'embroidery',
      title: 'Custom Embroidery',
      description: 'Add your brand identity through embroidered logos and personalized details.',
      iconName: 'Needle',
    },
    {
      id: 'hospitality',
      title: 'Hospitality Ready',
      description: 'Designed with hotels, restaurants, resorts and hospitality environments in mind.',
      iconName: 'Hotel',
    },
    {
      id: 'beautiful-tables',
      title: 'Made for Beautiful Tables',
      description: 'Practical textiles with a refined visual character.',
      iconName: 'UtensilsCrossed',
    },
  ] as FeaturePillar[],
  process: [
    {
      step: '01',
      title: 'Select',
      description: 'Choose the textile, style, colorway, and hem finish suitable for your establishment.',
    },
    {
      step: '02',
      title: 'Craft',
      description: 'Each piece is carefully prepared, cut, tailored, and hand-finished by skilled textile artisans.',
    },
    {
      step: '03',
      title: 'Personalise',
      description: 'Add your custom hotel crest, restaurant monogram, or embroidery where required.',
    },
    {
      step: '04',
      title: 'Deliver',
      description: 'Carefully packaged and ready for your dining room, hospitality team, or event venue.',
    },
  ] as ProcessStep[],
  gallery: [
    {
      id: 'g1',
      title: 'Handcrafted Dinner Napkins',
      category: 'Table Napkins',
      image: '/images/table-napkins.jpg',
      alt: 'Handcrafted linen table napkin folded in dinner fold on porcelain dinner plate',
    },
    {
      id: 'g2',
      title: 'Textured Linen Table Runner',
      category: 'Table Runners',
      image: '/images/table-runners.jpg',
      alt: 'Textured natural linen table runner laid across an artisanal wood dining table',
    },
    {
      id: 'g3',
      title: 'Draped Banquet Tablecloth',
      category: 'Table Cloths',
      image: '/images/table-cloths.jpg',
      alt: 'Floor length draped white linen tablecloth on luxury restaurant dining table',
    },
    {
      id: 'g4',
      title: 'Pocket Cutlery Serviette',
      category: 'Cutlery Serviettes',
      image: '/images/cutlery-serviettes.jpg',
      alt: 'Folded linen cutlery serviette with polished silverware tucked in pocket',
    },
    {
      id: 'g5',
      title: 'Custom Embroidered Chef Aprons',
      category: 'Aprons',
      image: '/images/aprons.jpg',
      alt: 'Chefs wearing custom embroidered hospitality chef aprons',
    },
    {
      id: 'g6',
      title: 'Bespoke Gold Logo Embroidery',
      category: 'Custom Embroidery',
      image: '/images/embroidery-with-logo.jpg',
      alt: 'High-density metallic gold monogram logo embroidery on linen fabric',
    },
  ] as GalleryItem[],
  productOptions: [
    'Table Napkins / Serviettes',
    'Table Runners',
    'Table Cloths',
    'Cutlery Serviettes',
    'Aprons',
    'Custom Embroidery',
    'Other',
  ],
};
